project:
  type: website

website:
  title: "Sporting Musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CarmenCiardiello
      - icon: twitter
        href: https://twitter.com/cdciardiello
      - icon: linkedin
        href: https://www.linkedin.com/in/carmen-ciardiello-01522913a/
      - icon: archive
        href: https://sabermetricmusings.blogspot.com/
    left: 
      - text: Batter Table
        href: batter_table.qmd
      - text: Skater EV RAPM Data
        href: skater_ev_rapm_tables.qmd
format:
  html:
    theme: minty
    css: styles.css



