project:
  type: website

website:
  title: "more-musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CarmenCiardiello/more-musings
      - icon: twitter
        href: https://twitter.com/cdciardiello
format:
  html:
    theme: minty
    css: styles.css



