project:
  type: website

website:
  title: "Sporting Musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CarmenCiardiello/more-musings
      - icon: twitter
        href: https://twitter.com/cdciardiello
      - icon: linkedin
        href: https://www.linkedin.com/in/carmen-ciardiello-01522913a/
      - icon: archive
        href: https://sabermetricmusings.blogspot.com/
format:
  html:
    theme: minty
    css: styles.css



